# Sample LLM configuration file for my-config package

providers:
  openai:
    api_key: "your-openai-api-key"
    base_url: "https://api.openai.com/v1"
    models:
      - name: "gpt-4"
        model: "gpt-4"
        tags: ["chat", "completion", "advanced"]
        description: "Advanced language model with strong reasoning capabilities"
      - name: "gpt-3.5-turbo"
        model: "gpt-3.5-turbo"
        tags: ["chat", "completion", "fast"]
        description: "Fast and efficient language model for most tasks"

  anthropic:
    api_key: "your-anthropic-api-key"
    base_url: "https://api.anthropic.com/v1"
    models:
      - name: "claude-3-opus"
        model: "claude-3-opus-20240229"
        tags: ["chat", "completion", "advanced"]
        description: "Advanced reasoning and instruction following"
      - name: "claude-3-sonnet"
        model: "claude-3-sonnet-20240229"
        tags: ["chat", "completion", "balanced"]
        description: "Balanced performance and efficiency"

  cohere:
    api_key: "your-cohere-api-key"
    base_url: "https://api.cohere.ai/v1"
    models:
      - name: "command"
        model: "command"
        tags: ["completion", "instruction"]
        description: "Instruction-following language model"
      - name: "embed"
        model: "embed-english-v3.0"
        tags: ["embedding"]
        description: "Text embedding model for semantic search"